name: shonenx
description: >
  🚀 ShonenX is a blazing-fast, modern, and user-friendly anime streaming app built with Flutter.
  Stream your favorite anime, keep track of your watch progress, and explore trending shows — 
  all in one place. Built with ❤️ by Darkx-dev.

publish_to: "none"

version: 1.6.9+8

environment:
  sdk: ">=3.5.0 <3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.7.1
  http: ^1.3.0
  html: ^0.15.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_carousel_widget: ^3.1.0
  grouped_list: ^6.0.0
  cached_network_image: ^3.4.1
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  media_kit_libs_android_video: ^1.3.7
  device_info_plus: ^11.2.1
  window_manager: ^0.4.3
  iconsax: ^0.0.8
  uuid: ^4.5.1
  smooth_page_indicator: ^1.2.0+3
  skeletonizer: ^1.4.3
  flutter_staggered_animations: ^1.1.1
  graphql_flutter: ^5.2.0-beta.8
  flutter_web_auth_2: ^4.1.0
  flutter_secure_storage:
    git:
      url: https://github.com/juliansteenbakker/flutter_secure_storage.git
      ref: master
      path: flutter_secure_storage
  url_launcher: ^6.3.1
  awesome_snackbar_content: ^0.1.5
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  flex_color_scheme: ^8.0.2
  rename: ^3.0.2
  image: ^4.5.3
  desktop_webview_window: ^0.2.3
  screen_brightness: ^2.1.2
  flutter_volume_controller: ^1.3.3
  media_kit_libs_linux: ^1.2.1
  permission_handler: ^12.0.0+1
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  pseudom: ^1.0.1
  xpath_selector_html_parser: ^3.0.1
  bot_toast: ^4.1.3
  flutter_inappwebview: ^6.1.5
  js_packer: ^0.0.5
  encrypt: ^5.0.3
  crypto: ^3.0.6
  riverpod_annotation: ^2.6.1
  path: ^1.9.0
  http_interceptor: ^2.0.0
  package_info_plus: ^8.0.0
  d4rt: 0.1.0
  collection: ^1.19.1
  dio: ^5.9.0
  install_plugin: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  json_serializable: ^6.0.1

dependency_overrides: 
  analyzer: ^7.4.5
  collection: ^1.19.1

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/app_icon-modified-2.png
    - .env

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icons/app_icon-modified-2.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon-modified-2.png"