name: Android Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history to get previous tags

      # 2. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      # 3. Install Android SDK + CMake
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: 25.2.9519653

      - name: Install CMake 3.18.1
        run: |
          yes | sdkmanager "cmake;3.18.1"
          echo "cmake.dir=$ANDROID_HOME/cmake/3.18.1" >> $GITHUB_WORKSPACE/android/local.properties

      # 4. Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Create .env file
      - name: Create .env file
        run: |
          echo "ANILIST_CLIENT_ID=${{ secrets.ANILIST_CLIENT_ID }}" >> .env
          echo "ANILIST_CLIENT_SECRET=${{ secrets.ANILIST_CLIENT_SECRET }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env
        shell: bash

      # 6. Generate structured release notes
      - name: Generate release notes
        id: changelog
        run: |
          # Get the latest tag before this release
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "Last tag: $LAST_TAG"

          # Get commits since last tag
          COMMITS=$(git log $LAST_TAG..HEAD --pretty=format:'%s')

          # Categorize commits by type (conventional commits)
          echo "## Changelog" > release_notes.md
          for TYPE in feat fix perf style refactor docs chore; do
            echo "### $TYPE" >> release_notes.md
            echo "$COMMITS" | grep -i "^$TYPE" | sed "s/^$TYPE: /- /" >> release_notes.md || true
            echo "" >> release_notes.md
          done

          # Save to output
          RELEASE_NOTES=$(cat release_notes.md)
          echo "$RELEASE_NOTES"
          echo "::set-output name=notes::$RELEASE_NOTES"

      # 7. Build APKs (split per ABI)
      - name: Build APK (split per ABI)
        run: flutter build apk --release --split-per-abi

      # 8. Create GitHub Release with APKs and changelog
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/*.apk
          body: ${{ steps.changelog.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
